/**
 * Public type surface for wire DTOs, operation inputs/results, and branded primitives.
 *
 * Persisted storage shapes live on sibling subpaths — import them directly when building
 * repositories or custom backends:
 * `@bnomei/emdash-mika/types/documents`, `/types/aggregates`, `/types/operational`.
 * Agent-facing vocabulary lives on `@bnomei/emdash-mika/agent`.
 */
/** Stable API error codes and provider capability flags from the wire DTO layer. */
export { MIKA_ERROR_CODES, MIKA_PROVIDER_CAPABILITIES } from "../api/types";
/** Wire DTOs and operation input shapes shared by clients, actions, and handlers. */
export type {
  AccountDTO,
  AccountDeleteInput,
  AccountExportDTO,
  AccountExportDownloadDTO,
  AccountExportDownloadInput,
  AccountExportInput,
  AccountExportStatusInput,
  AccountPortalInput,
  AddCartItemInput,
  AdminActionResultDTO,
  AppliedCouponDTO,
  ApplyCouponInput,
  AvailabilityDTO,
  AvailabilityStatus,
  CartDTO,
  CartLineDTO,
  CartQuoteAdjustmentDTO,
  CartQuoteDTO,
  CartQuoteInput,
  CartQuoteLineDTO,
  CartQuoteStatusDTO,
  CheckoutCancelInput,
  CheckoutCustomerInput,
  CheckoutPreviewDTO,
  CheckoutPreviewInput,
  CheckoutPreviewProofRequirementDTO,
  CheckoutPreviewStatusDTO,
  CheckoutSessionDTO,
  CheckoutStatusDTO,
  CheckoutStatusInput,
  ContentRefDTO,
  CustomerDTO,
  DownloadDTO,
  DownloadIssueInput,
  DownloadResolutionDTO,
  EmailResendInput,
  EntitlementDTO,
  EntitlementGrantInput,
  EntitlementRevokeInput,
  LicenseRevokeInput,
  MagicLinkRequestInput,
  MagicLinkVerifyInput,
  MergeCartInput,
  MergeWishlistInput,
  MikaApiResult,
  MikaClientEffect,
  MikaError,
  MikaErrorCode,
  MikaProviderCapability,
  MoneyDTO,
  MoveWishlistItemToCartInput,
  OrderCancelInput,
  OrderInvoiceDTO,
  OrderInvoiceInput,
  OrderRefundInput,
  OrderSummaryDTO,
  PriceDTO,
  ProviderHealthDTO,
  ProviderHealthInput,
  ProviderSyncInput,
  ReleaseExpiredReservationsInput,
  RemoveCartItemInput,
  RemoveCouponInput,
  RemoveWishlistItemInput,
  SaveCartLineForLaterInput,
  SellableDTO,
  StartCheckoutInput,
  StockAdjustInput,
  SubscriptionActionInput,
  SubscriptionDTO,
  UpdateCartItemInput,
  VariantOptionGroupDTO,
  VariantOptionValueDTO,
  WebhookReceiveDTO,
  WebhookReceiveInput,
  WebhookReplayInput,
  WishlistDTO,
  WishlistItemDTO,
  WishlistItemInput,
} from "../api/types";
/** Branded primitive ids, money, status enums, and JSON helpers for the storage model. */
export {
  createCurrencyCode,
  createISODateTime,
  createMikaId,
  createProviderName,
  isCurrencyCode,
  isISODateTime,
  isJsonObject,
  isJsonValue,
  isMikaId,
  isProviderName,
} from "./primitives";
export type {
  AggregatePayload,
  CartStatus,
  CheckoutStatus,
  ContentRef,
  CurrencyCode,
  EmailStatus,
  EntitlementStatus,
  FulfillmentKind,
  ISODateTime,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  MikaId,
  MikaSchemaVersion,
  Money,
  OrderStatus,
  PaymentStatus,
  ProviderName,
  PurchaseMode,
  StockMovementReason,
  StockPolicy,
  StockReservationStatus,
  SubscriptionStatus,
  Timestamped,
  TokenPurpose,
  TokenStatus,
  WebhookStatus,
  WishlistStatus,
} from "./primitives";
