/**
 * Public type surface for wire DTOs, agent manifest constants, and branded primitives.
 *
 * Persisted storage shapes live on sibling subpaths — import them directly when building
 * repositories or custom backends:
 * `@bnomei/emdash-mika/types/documents`, `/types/aggregates`, `/types/operational`.
 * This entry re-exports API DTOs, agent contracts, and primitives only.
 */
/** Stable API error codes and provider capability flags from the wire DTO layer. */
export { MIKA_ERROR_CODES, MIKA_PROVIDER_CAPABILITIES } from "../api/types";
/** Agent manifest constants for capability, risk, and idempotency policy discovery. */
export {
  MIKA_ACTION_RUN_STATUSES,
  MIKA_AGENT_ACTOR_REQUIREMENTS,
  MIKA_AGENT_APPROVAL_STATUSES,
  MIKA_AGENT_CAPABILITIES,
  MIKA_AGENT_CONFIRMATION_POLICIES,
  MIKA_AGENT_EFFECTS,
  MIKA_AGENT_IDEMPOTENCY_KEY_HEADER,
  MIKA_AGENT_IDEMPOTENCY_POLICIES,
  MIKA_AGENT_IDEMPOTENCY_SCOPES,
  MIKA_AGENT_MANIFEST_VERSION,
  MIKA_AGENT_PROOF_KINDS,
  MIKA_AGENT_RESOURCES,
  MIKA_AGENT_RISKS,
  MIKA_AGENT_VISIBILITIES,
} from "../api/agent-types";
/** Agent actor, proof, approval, and manifest descriptor types. */
export type {
  MikaActorContext,
  MikaActorKind,
  MikaActionRun,
  MikaActionRunError,
  MikaActionRunStatus,
  MikaAgentActionAccept,
  MikaAgentActionDescriptor,
  MikaAgentActorRequirement,
  MikaAgentApprovalRef,
  MikaAgentApprovalStatus,
  MikaAgentCapability,
  MikaAgentConfirmationPolicy,
  MikaAgentEffect,
  MikaAgentIdempotencyMetadata,
  MikaAgentIdempotencyPolicy,
  MikaAgentIdempotencyScope,
  MikaAgentManifest,
  MikaAgentOperationHttpMethod,
  MikaAgentOperationMetadata,
  MikaAgentOperationTransport,
  MikaAgentProofKind,
  MikaAgentProofRef,
  MikaAgentResource,
  MikaAgentRisk,
  MikaAgentVisibility,
  MikaAuthorizationScope,
  MikaConsentProofRef,
  MikaMandateRef,
  MikaPaymentAuthorizationRef,
  MikaReceiptRef,
} from "../api/agent-types";
/** Wire DTOs and operation input shapes shared by clients, actions, and handlers. */
export type {
  AccountDTO,
  AccountDeleteInput,
  AccountExportDTO,
  AccountExportDownloadDTO,
  AccountExportDownloadInput,
  AccountExportInput,
  AccountExportStatusInput,
  AccountPortalInput,
  AddCartItemInput,
  AdminActionResultDTO,
  AppliedCouponDTO,
  ApplyCouponInput,
  AvailabilityDTO,
  AvailabilityStatus,
  CartDTO,
  CartLineDTO,
  CartQuoteAdjustmentDTO,
  CartQuoteDTO,
  CartQuoteInput,
  CartQuoteLineDTO,
  CartQuoteStatusDTO,
  CheckoutCustomerInput,
  CheckoutPreviewDTO,
  CheckoutPreviewInput,
  CheckoutPreviewProofRequirementDTO,
  CheckoutPreviewStatusDTO,
  CheckoutSessionDTO,
  CheckoutStatusDTO,
  ContentRefDTO,
  CustomerDTO,
  DownloadDTO,
  DownloadIssueInput,
  DownloadResolutionDTO,
  EmailResendInput,
  EntitlementDTO,
  EntitlementGrantInput,
  EntitlementRevokeInput,
  LicenseRevokeInput,
  MagicLinkRequestInput,
  MagicLinkVerifyInput,
  MergeCartInput,
  MergeWishlistInput,
  MikaApiResult,
  MikaClientEffect,
  MikaError,
  MikaErrorCode,
  MikaProviderCapability,
  MoneyDTO,
  MoveWishlistItemToCartInput,
  OrderCancelInput,
  OrderInvoiceDTO,
  OrderInvoiceInput,
  OrderRefundInput,
  OrderSummaryDTO,
  PriceDTO,
  ProviderHealthDTO,
  ProviderHealthInput,
  ProviderSyncInput,
  ReleaseExpiredReservationsInput,
  RemoveCartItemInput,
  RemoveCouponInput,
  RemoveWishlistItemInput,
  SaveCartLineForLaterInput,
  SellableDTO,
  StartCheckoutInput,
  StockAdjustInput,
  SubscriptionActionInput,
  SubscriptionDTO,
  UpdateCartItemInput,
  VariantOptionGroupDTO,
  VariantOptionValueDTO,
  WebhookReceiveDTO,
  WebhookReceiveInput,
  WebhookReplayInput,
  WishlistDTO,
  WishlistItemDTO,
  WishlistItemInput,
} from "../api/types";
/** Branded primitive ids, money, status enums, and JSON helpers for the storage model. */
export {
  createCurrencyCode,
  createISODateTime,
  createMikaId,
  createProviderName,
  isCurrencyCode,
  isISODateTime,
  isJsonObject,
  isJsonValue,
  isMikaId,
  isProviderName,
} from "./primitives";
export type {
  AggregatePayload,
  CartStatus,
  CheckoutStatus,
  ContentRef,
  CurrencyCode,
  EmailStatus,
  EntitlementStatus,
  FulfillmentKind,
  ISODateTime,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  MikaId,
  MikaSchemaVersion,
  Money,
  OrderStatus,
  PaymentStatus,
  ProviderName,
  PurchaseMode,
  StockMovementReason,
  StockPolicy,
  StockReservationStatus,
  SubscriptionStatus,
  Timestamped,
  TokenPurpose,
  TokenStatus,
  WebhookStatus,
  WishlistStatus,
} from "./primitives";
