/**
 * Operation and route-only definition catalogs (const maps + form-action normalizers).
 */
import { omitUndefined } from "../internal/object";
import { createMikaId } from "../types/primitives";
import { normalizeMikaCheckoutCustomer, parseMikaPurchaseField } from "./form-contracts";
import { agentOperationMetadata } from "./operation-agent-metadata";
import {
  defineMikaOperation,
  defineMikaOperations,
  defineMikaRouteOnlyDefinitions,
  formAction,
  jsonAction,
  MikaActionInputError,
} from "./operation-define";
import {
  accountExportDownloadInputSchema,
  accountExportStatusInputSchema,
  addCartItemInputSchema,
  applyCouponInputSchema,
  cartAddFormInputSchema,
  cartQuoteInputSchema,
  checkoutCancelInputSchema,
  checkoutPreviewInputSchema,
  checkoutStartFormInputSchema,
  checkoutStatusInputSchema,
  contentRefInputSchema,
  downloadIssueInputSchema,
  downloadResolveInputSchema,
  emailResendInputSchema,
  entitlementGrantInputSchema,
  entitlementRevokeInputSchema,
  licenseRevokeInputSchema,
  magicLinkRequestInputSchema,
  magicLinkVerifyInputSchema,
  mergeCartInputSchema,
  mergeWishlistInputSchema,
  moveWishlistItemToCartInputSchema,
  orderCancelInputSchema,
  orderInvoiceInputSchema,
  orderRefundInputSchema,
  providerHealthInputSchema,
  providerSyncInputSchema,
  releaseExpiredReservationsInputSchema,
  removeCartItemInputSchema,
  removeCouponInputSchema,
  removeWishlistItemInputSchema,
  returnToInputSchema,
  saveCartLineForLaterInputSchema,
  startCheckoutInputSchema,
  stockAdjustInputSchema,
  stockAvailabilityInputSchema,
  subscriptionCancelInputSchema,
  subscriptionChangeInputSchema,
  subscriptionRenewInputSchema,
  updateCartItemInputSchema,
  webhookReceiveInputSchema,
  webhookReplayInputSchema,
  wishlistItemInputSchema,
  type z,
} from "./validation";

/** Routes without backing API operations (admin manifest and action runner). */
export const mikaRouteOnlyDefinitions = defineMikaRouteOnlyDefinitions({
  actionsManifest: {
    routeKey: "actionsManifest",
    routePath: ".well-known/actions",
    public: false,
  },
  actionsRunner: {
    routeKey: "actionsRunner",
    routePath: ".well-known/actions/run",
    public: false,
  },
});

type CartAddFormInput = z.infer<typeof cartAddFormInputSchema>;
type CheckoutStartFormInput = z.infer<typeof checkoutStartFormInputSchema>;
// The normalize seam feeds runMikaOperation, which types the call input as z.infer<operationSchema>.
// Annotating each normalizer's return with that exact type turns a drift between the form action
// and the operation it dispatches to (e.g. a renamed or dropped field) into a compile error.
type CartAddOperationInput = z.infer<typeof addCartItemInputSchema>;
type CheckoutStartOperationInput = z.infer<typeof startCheckoutInputSchema>;

function normalizeCartAddActionInput(input: CartAddFormInput): CartAddOperationInput {
  const purchase = parseMikaPurchaseField(input.purchase);
  const purchaseSellableId = parsePurchaseMikaId(purchase.sellableId, "sellableId");
  const purchasePriceId = parsePurchaseMikaId(purchase.priceId, "priceId");
  const sellableId = purchaseSellableId ?? input.sellableId;
  const priceId = purchasePriceId ?? input.priceId;

  if (!sellableId) {
    throw new MikaActionInputError("sellableId is required.");
  }

  return omitUndefined({
    sellableId,
    priceId: priceId || undefined,
    variantKey: input.variantKey,
    variantOptions: input.variantOptions,
    quantity: input.quantity,
    returnTo: input.returnTo,
  });
}

function normalizeCheckoutStartActionInput(
  input: CheckoutStartFormInput,
): CheckoutStartOperationInput {
  const customer = normalizeMikaCheckoutCustomer(input);

  return omitUndefined({
    cartId: input.cartId,
    sellableId: input.sellableId,
    priceId: input.priceId,
    quantity: input.quantity,
    provider: input.provider,
    couponCode: input.couponCode,
    customer,
    customFields: input.customFields,
    successPath: input.successPath,
    cancelPath: input.cancelPath,
    returnTo: input.returnTo,
  });
}

function parsePurchaseMikaId(value: string | null | undefined, field: string) {
  if (!value) return undefined;

  try {
    return createMikaId(value);
  } catch {
    throw new MikaActionInputError(`${field} is invalid.`);
  }
}

/** Full catalog of Mika API operations with schemas, routes, and dispatch closures. */
export const mikaOperationDefinitions = defineMikaOperations({
  catalogSellables: defineMikaOperation({
    namespace: "catalog",
    method: "sellables",
    routeKey: "catalogSellables",
    routePath: "catalog/sellables",
    httpMethod: "GET",
    transport: "search",
    public: true,
    requiresRequestContext: false,
    agent: agentOperationMetadata.catalogRead,
    schema: contentRefInputSchema,
    searchKeys: ["collection", "id", "locale"],
    action: jsonAction(),
    call: (api, _ctx, input) => api.catalog.sellables({ contentRef: input }),
  }),
  stockAvailability: defineMikaOperation({
    namespace: "stock",
    method: "availability",
    routeKey: "sellableAvailability",
    routePath: "sellables/availability",
    httpMethod: "GET",
    transport: "search",
    public: true,
    requiresRequestContext: false,
    agent: agentOperationMetadata.stockRead,
    schema: stockAvailabilityInputSchema,
    searchKeys: ["sellableId"],
    action: jsonAction(),
  }),
  cartGet: defineMikaOperation({
    namespace: "cart",
    method: "get",
    routeKey: "cart",
    routePath: "cart",
    httpMethod: "GET",
    transport: "none",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.cartRead,
  }),
  cartQuote: defineMikaOperation({
    namespace: "cart",
    method: "quote",
    routeKey: "cartQuote",
    routePath: "cart/quote",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.cartQuote,
    schema: cartQuoteInputSchema,
  }),
  cartAdd: defineMikaOperation({
    namespace: "cart",
    method: "add",
    routeKey: "cartItems",
    routePath: "cart/items",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.cartWrite,
    schema: addCartItemInputSchema,
    action: formAction({
      schema: cartAddFormInputSchema,
      normalize: normalizeCartAddActionInput,
    }),
  }),
  cartUpdate: defineMikaOperation({
    namespace: "cart",
    method: "update",
    routeKey: "cartItem",
    routePath: "cart/item",
    httpMethod: "PATCH",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.cartWrite,
    schema: updateCartItemInputSchema,
    action: formAction(),
  }),
  cartRemove: defineMikaOperation({
    namespace: "cart",
    method: "remove",
    routeKey: "cartItem",
    routePath: "cart/item",
    httpMethod: "DELETE",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.cartWrite,
    schema: removeCartItemInputSchema,
    action: formAction(),
  }),
  cartMerge: defineMikaOperation({
    namespace: "cart",
    method: "merge",
    routeKey: "cartMerge",
    routePath: "cart/merge",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.cartWrite,
    schema: mergeCartInputSchema,
    action: formAction(),
  }),
  cartApplyCoupon: defineMikaOperation({
    namespace: "cart",
    method: "applyCoupon",
    routeKey: "cartCoupon",
    routePath: "cart/coupon",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.cartWrite,
    schema: applyCouponInputSchema,
    action: formAction(),
  }),
  cartRemoveCoupon: defineMikaOperation({
    namespace: "cart",
    method: "removeCoupon",
    routeKey: "cartCoupon",
    routePath: "cart/coupon",
    httpMethod: "DELETE",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.cartWrite,
    schema: removeCouponInputSchema,
    action: formAction(),
  }),
  wishlistGet: defineMikaOperation({
    namespace: "wishlist",
    method: "get",
    routeKey: "wishlist",
    routePath: "wishlist",
    httpMethod: "GET",
    transport: "none",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.wishlistRead,
  }),
  wishlistAdd: defineMikaOperation({
    namespace: "wishlist",
    method: "add",
    routeKey: "wishlistItems",
    routePath: "wishlist/items",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.wishlistWrite,
    schema: wishlistItemInputSchema,
    action: formAction(),
  }),
  wishlistRemove: defineMikaOperation({
    namespace: "wishlist",
    method: "remove",
    routeKey: "wishlistItem",
    routePath: "wishlist/item",
    httpMethod: "DELETE",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.wishlistWrite,
    schema: removeWishlistItemInputSchema,
    action: formAction(),
  }),
  wishlistMoveToCart: defineMikaOperation({
    namespace: "wishlist",
    method: "moveToCart",
    routeKey: "wishlistMoveToCart",
    routePath: "wishlist/move-to-cart",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.wishlistWrite,
    schema: moveWishlistItemToCartInputSchema,
    action: formAction(),
  }),
  wishlistSaveForLater: defineMikaOperation({
    namespace: "wishlist",
    method: "saveForLater",
    routeKey: "wishlistSaveForLater",
    routePath: "wishlist/save-for-later",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.wishlistWrite,
    schema: saveCartLineForLaterInputSchema,
    action: formAction(),
  }),
  wishlistMerge: defineMikaOperation({
    namespace: "wishlist",
    method: "merge",
    routeKey: "wishlistMerge",
    routePath: "wishlist/merge",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.wishlistWrite,
    schema: mergeWishlistInputSchema,
    action: formAction(),
  }),
  checkoutStart: defineMikaOperation({
    namespace: "checkout",
    method: "start",
    routeKey: "checkout",
    routePath: "checkout",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.checkoutHandoff,
    schema: startCheckoutInputSchema,
    action: formAction({
      schema: checkoutStartFormInputSchema,
      normalize: normalizeCheckoutStartActionInput,
    }),
  }),
  checkoutPreview: defineMikaOperation({
    namespace: "checkout",
    method: "preview",
    routeKey: "checkoutPreview",
    routePath: "checkout/preview",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.checkoutPreview,
    schema: checkoutPreviewInputSchema,
  }),
  checkoutStatus: defineMikaOperation({
    namespace: "checkout",
    method: "status",
    routeKey: "checkoutStatus",
    routePath: "checkout/status",
    httpMethod: "GET",
    transport: "search",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.checkoutRead,
    schema: checkoutStatusInputSchema,
    searchKeys: ["checkoutId", "token"],
    action: jsonAction(),
  }),
  checkoutCancel: defineMikaOperation({
    namespace: "checkout",
    method: "cancel",
    routeKey: "checkoutAbandon",
    routePath: "checkout/abandon",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.checkoutHandoff,
    schema: checkoutCancelInputSchema,
  }),
  magicLinkRequest: defineMikaOperation({
    namespace: "magicLink",
    method: "request",
    routeKey: "magicLink",
    routePath: "magic-link",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.magicLinkWrite,
    schema: magicLinkRequestInputSchema,
    action: formAction(),
  }),
  magicLinkVerify: defineMikaOperation({
    namespace: "magicLink",
    method: "verify",
    routeKey: "magicLinkVerify",
    routePath: "magic-link/verify",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.magicLinkWrite,
    schema: magicLinkVerifyInputSchema,
    action: formAction(),
  }),
  accountGet: defineMikaOperation({
    namespace: "account",
    method: "get",
    routeKey: "account",
    routePath: "account",
    httpMethod: "GET",
    transport: "none",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.accountRead,
  }),
  accountExport: defineMikaOperation({
    namespace: "account",
    method: "export",
    routeKey: "accountExport",
    routePath: "account/export",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.accountWrite,
    schema: returnToInputSchema,
    action: formAction(),
  }),
  accountExportStatus: defineMikaOperation({
    namespace: "account",
    method: "exportStatus",
    routeKey: "accountExportStatus",
    routePath: "account/export/status",
    httpMethod: "GET",
    transport: "search",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.accountRead,
    schema: accountExportStatusInputSchema,
    searchKeys: ["exportId"],
    action: jsonAction(),
  }),
  accountExportDownload: defineMikaOperation({
    namespace: "account",
    method: "exportDownload",
    routeKey: "accountExportDownload",
    routePath: "account/export/download",
    httpMethod: "GET",
    transport: "search",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.accountRead,
    schema: accountExportDownloadInputSchema,
    searchKeys: ["exportId", "token"],
  }),
  accountExportDownloadConsume: defineMikaOperation({
    namespace: "account",
    method: "exportDownloadConsume",
    routeKey: "accountExportDownload",
    routePath: "account/export/download",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    apiMethod: false,
    agent: agentOperationMetadata.accountRead,
    schema: accountExportDownloadInputSchema,
    call: (api, ctx, operationInput) =>
      api.account.exportDownload(ctx, { ...operationInput, consumeToken: true }),
  }),
  accountDelete: defineMikaOperation({
    namespace: "account",
    method: "delete",
    routeKey: "accountDelete",
    routePath: "account/delete",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.accountWrite,
    schema: returnToInputSchema,
    action: formAction(),
  }),
  accountPortal: defineMikaOperation({
    namespace: "account",
    method: "portal",
    routeKey: "accountPortal",
    routePath: "account/portal",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.accountWrite,
    schema: returnToInputSchema,
    action: formAction(),
  }),
  subscriptionCancel: defineMikaOperation({
    namespace: "subscription",
    method: "cancel",
    routeKey: "subscriptionCancel",
    routePath: "subscriptions/cancel",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.subscriptionWrite,
    schema: subscriptionCancelInputSchema,
    action: formAction(),
  }),
  subscriptionChange: defineMikaOperation({
    namespace: "subscription",
    method: "change",
    routeKey: "subscriptionChange",
    routePath: "subscriptions/change",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.subscriptionWrite,
    schema: subscriptionChangeInputSchema,
    action: formAction(),
  }),
  subscriptionRenew: defineMikaOperation({
    namespace: "subscription",
    method: "renew",
    routeKey: "subscriptionRenew",
    routePath: "subscriptions/renew",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.subscriptionWrite,
    schema: subscriptionRenewInputSchema,
    action: formAction(),
  }),
  downloadResolve: defineMikaOperation({
    namespace: "download",
    method: "resolve",
    routeKey: "download",
    routePath: "download",
    httpMethod: "GET",
    transport: "search",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.downloadRead,
    schema: downloadResolveInputSchema,
    searchKeys: ["token"],
  }),
  downloadConfirm: defineMikaOperation({
    namespace: "download",
    method: "confirm",
    routeKey: "downloadConfirm",
    routePath: "download/confirm",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.downloadRead,
    schema: downloadResolveInputSchema,
    action: formAction(),
  }),
  orderInvoice: defineMikaOperation({
    namespace: "order",
    method: "invoice",
    routeKey: "orderInvoice",
    routePath: "orders/invoice",
    httpMethod: "GET",
    transport: "search",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.orderRead,
    schema: orderInvoiceInputSchema,
    searchKeys: ["orderId", "token", "returnTo"],
  }),
  webhookReceive: defineMikaOperation({
    namespace: "webhook",
    method: "receive",
    routeKey: "webhook",
    routePath: "webhooks",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: true,
    agent: agentOperationMetadata.webhookReceive,
    schema: webhookReceiveInputSchema,
  }),
  adminProviderHealth: defineMikaOperation({
    namespace: "admin",
    method: "providerHealth",
    routeKey: "adminProviderHealth",
    routePath: "admin/provider/health",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminRead,
    schema: providerHealthInputSchema,
  }),
  adminProviderSync: defineMikaOperation({
    namespace: "admin",
    method: "providerSync",
    routeKey: "adminProviderSync",
    routePath: "admin/provider/sync",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: providerSyncInputSchema,
  }),
  adminStockAdjust: defineMikaOperation({
    namespace: "admin",
    method: "stockAdjust",
    routeKey: "adminStockAdjust",
    routePath: "admin/stock/adjust",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: stockAdjustInputSchema,
  }),
  adminStockReleaseExpiredReservations: defineMikaOperation({
    namespace: "admin",
    method: "releaseExpiredReservations",
    routeKey: "adminStockReleaseExpiredReservations",
    routePath: "admin/stock/release-expired-reservations",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: releaseExpiredReservationsInputSchema,
  }),
  adminWebhookReplay: defineMikaOperation({
    namespace: "admin",
    method: "webhookReplay",
    routeKey: "adminWebhookReplay",
    routePath: "admin/webhooks/replay",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: webhookReplayInputSchema,
  }),
  adminOrderRefund: defineMikaOperation({
    namespace: "admin",
    method: "orderRefund",
    routeKey: "adminOrderRefund",
    routePath: "admin/orders/refund",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: orderRefundInputSchema,
  }),
  adminOrderCancel: defineMikaOperation({
    namespace: "admin",
    method: "orderCancel",
    routeKey: "adminOrderCancel",
    routePath: "admin/orders/cancel",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: orderCancelInputSchema,
  }),
  adminEntitlementGrant: defineMikaOperation({
    namespace: "admin",
    method: "entitlementGrant",
    routeKey: "adminEntitlementGrant",
    routePath: "admin/entitlements/grant",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: entitlementGrantInputSchema,
  }),
  adminEntitlementRevoke: defineMikaOperation({
    namespace: "admin",
    method: "entitlementRevoke",
    routeKey: "adminEntitlementRevoke",
    routePath: "admin/entitlements/revoke",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: entitlementRevokeInputSchema,
  }),
  adminEmailResend: defineMikaOperation({
    namespace: "admin",
    method: "emailResend",
    routeKey: "adminEmailResend",
    routePath: "admin/emails/resend",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: emailResendInputSchema,
  }),
  adminLicenseRevoke: defineMikaOperation({
    namespace: "admin",
    method: "licenseRevoke",
    routeKey: "adminLicenseRevoke",
    routePath: "admin/licenses/revoke",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: licenseRevokeInputSchema,
  }),
  adminDownloadIssue: defineMikaOperation({
    namespace: "admin",
    method: "downloadIssue",
    routeKey: "adminDownloadIssue",
    routePath: "admin/downloads/issue",
    httpMethod: "POST",
    transport: "body",
    public: false,
    requiresRequestContext: false,
    agent: agentOperationMetadata.adminWrite,
    schema: downloadIssueInputSchema,
  }),
});

/** One registered operation definition (schema, route, agent metadata, and call binding). */
export type MikaApiOperation =
  (typeof mikaOperationDefinitions)[keyof typeof mikaOperationDefinitions];
/** Route-only entry without a backing API operation (manifest and action runner). */
export type MikaRouteOnlyDefinition =
  (typeof mikaRouteOnlyDefinitions)[keyof typeof mikaRouteOnlyDefinitions];
